import { requireSession } from "./auth_beta.js";
import { mountShell, getActiveTournament, setActiveTournament } from "./shell_beta.js";
import { escapeHtml, formatDate, notify, showState, confirmAction, setBusy } from "./ui_beta.js";
import { listAvailableTournaments, loadGrid, getMemberPlayer, searchPlayers, ensurePlayer, createManualPlayer, lockLine, unlockLine, registerPlayers, reserveSlot, releaseSlot, blockSlot, moveRegistration, validateSlotChoice, isEmpty, isReservation, subscribeGrid } from "./registration_service_beta.js";

const context = await requireSession();
const isAdmin = context.profile.role === "admin";
mountShell({context,activeStep:1});

const $ = selector => document.querySelector(selector);
const state = { tournaments:[], tournament:null, blocks:[], lines:[], slots:[], member:null, activeSlot:null, moveSource:null, selected:[], unsubscribe:null, searchTimer:null, loading:false, viewFilter:"all" };
const dom = { page:$("#pageState"),strip:$("#tournamentStrip"),tabs:$("#gridViewTabs"),gridSearch:$("#gridPlayerSearch"),grid:$("#gridHost"),drawer:$("#playerDrawer"),slotDrawer:$("#slotDrawer"),search:$("#playerSearch"),results:$("#searchResults"),summary:$("#selectionSummary"),save:$("#saveRegistration"),reserve:$("#reserveButton"),manual:$("#manualPanel") };
if(isAdmin) $("#whatsappButton")?.remove();
if(isAdmin) $("#exportGridButton").hidden=false; else $("#exportGridButton")?.remove();

const statusLabel = value => ({open:"Inscripción abierta",closed:"Inscripción cerrada",officialized:"Guardado",archived:"Archivado"})[value] || value;
const canEdit = () => isAdmin ? ["open","closed","officialized"].includes(state.tournament?.status) : state.tournament?.status === "open";
const requiresPartner = () => state.tournament?.game_modes?.requires_partner === true;
const byLine = lineId => state.slots.filter(slot => slot.starting_line_id === lineId).sort((a,b)=>a.slot_number-b.slot_number);
const isBisLine = line => /\bBIS\b/i.test(String(line?.label||""));
const blockLines = blockId => state.lines.filter(line => line.starting_block_id === blockId).sort((a,b)=>{
  if(state.tournament?.start_type==="simultanea"){
    const holeDifference=Number(a.starting_hole||0)-Number(b.starting_hole||0);
    if(holeDifference)return holeDifference;
    const bisDifference=Number(isBisLine(a))-Number(isBisLine(b));
    if(bisDifference)return bisDifference;
  }
  return Number(a.display_order||0)-Number(b.display_order||0);
});
const lockOther = slot => slot.lock_expires_at && new Date(slot.lock_expires_at)>new Date() && slot.locked_by_player_id !== state.member?.id && !isReservation(slot);
const isOwn = slot => isAdmin || String(slot.linked_player_id||"")===String(state.member?.id||"") || String(slot.created_by_player_id||"")===String(state.member?.id||"") || String(slot.locked_by_player_id||"")===String(state.member?.id||"");
const slotKind = slot => { if(slot.participant_type==="blocked")return"blocked";if(isReservation(slot))return"reserved";if(!slot.aag_member_number)return"manual";return Number(slot.option_club_id)===408 || /VILLA MAR[IÍ]A/i.test(slot.club_name||"") ? "member":"visitor"; };
const lineLabel = line => state.tournament?.start_type === "simultanea" ? (line.label || `Hoyo ${line.starting_hole}`) : String(line.line_time||"").slice(0,5);
const lineSub = line => state.tournament?.start_type === "simultanea" ? String(line.line_time||"").slice(0,5) : `Hoyo ${line.starting_hole}`;

function renderStrip(){const t=state.tournament;const occupied=state.slots.filter(s=>!isEmpty(s)&&s.participant_type!=="blocked"&&!isReservation(s)).length;const free=state.slots.filter(isEmpty).length;dom.strip.innerHTML=`<div class="tournament-main"><span class="status ${t.status==="open"?"open":"pending"}">${escapeHtml(statusLabel(t.status))}</span><h2>${escapeHtml(t.name)}</h2><div class="meta">${formatDate(t.tournament_date)} · ${escapeHtml(t.game_modes?.name||"")} · ${t.start_type==="simultanea"?"Salida simultánea":"Salida secuencial"}</div></div><div class="metric"><strong>${occupied}</strong><span>Jugadores</span></div><div class="metric"><strong>${free}</strong><span>Lugares libres</span></div><div class="metric"><strong>${state.lines.length}</strong><span>Líneas</span></div><div class="metric"><strong>${requiresPartner()?"Parejas":"Individual"}</strong><span>Participación</span></div>`;const summary=$("#gridSummary");if(summary)summary.textContent=`${occupied} inscriptos · ${free} lugares libres`;}

function renderSlot(slot){if(slot.participant_type==="blocked")return `<button class="slot blocked" data-slot="${slot.id}"><span class="slot-number">${slot.slot_number}</span><strong>Bloqueado</strong><span>Administración</span></button>`;if(isReservation(slot))return `<button class="slot reserved" data-slot="${slot.id}"><span class="slot-number">${slot.slot_number}</span><strong>Reservado</strong><span>${slot.notes==="RESERVA_ADMIN"?"Por administración":"Por 24 horas"}</span></button>`;if(isEmpty(slot))return `<button class="slot free ${lockOther(slot)?"locked":""}" data-slot="${slot.id}" ${!canEdit()||lockOther(slot)?"disabled":""}><span class="slot-number">${slot.slot_number}</span><strong>${lockOther(slot)?"Seleccionando…":"＋ Agregar"}</strong><span>Lugar libre</span></button>`;return `<button class="slot ${slotKind(slot)}" data-slot="${slot.id}"><span class="slot-number">${slot.slot_number}</span><strong>${escapeHtml(slot.display_name)}</strong><span class="slot-club">${escapeHtml(slot.club_name || (slot.aag_member_number?"AAG":"Jugador manual"))}</span></button>`;}
function screenBlockTitle(block){if(state.tournament?.start_type==="simultanea")return block.name||"Salida simultánea";const firstLine=blockLines(block.id)[0],fallback=/bloque\s*2/i.test(String(block.name||""))?10:1;return`Salida por Hoyo ${Number(firstLine?.starting_hole||fallback)}`}
function renderScreenLines(block,shotgun){const lines=blockLines(block.id),shiftBreak=shotgun?-1:shareShiftBreak(lines);return lines.map((line,index)=>`${index===shiftBreak?'<div class="screen-shift-divider"><span>Turno tarde</span></div>':""}<div class="slot-line ${shotgun?"shotgun":""}"><div class="slot-time">${escapeHtml(lineLabel(line))}<small class="line-label">${escapeHtml(lineSub(line))}</small></div>${byLine(line.id).map(renderSlot).join("")}</div>`).join("")}
function blockMatchesSearch(block,query){if(!query)return true;return blockLines(block.id).some(line=>byLine(line.id).some(slot=>`${slot.display_name||""} ${slot.aag_member_number||""}`.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").includes(query)));}
function renderGrid(){const shotgun=state.tournament?.start_type==="simultanea",query=(dom.gridSearch?.value||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""),blocks=state.blocks.filter(block=>(state.viewFilter==="all"||block.id===state.viewFilter)&&blockMatchesSearch(block,query));dom.grid.innerHTML=blocks.map(block=>`<article class="grid-block"><header class="grid-block-head"><div><h2>${escapeHtml(screenBlockTitle(block))}</h2><div class="subtle">${escapeHtml(String(block.start_time||"").slice(0,5))}</div></div><span class="status neutral">${blockLines(block.id).length} líneas</span></header><div class="grid-block-body">${renderScreenLines(block,shotgun)||'<div class="empty-state">Este bloque no tiene líneas.</div>'}</div></article>`).join("")||`<div class="empty-state">${query?"No hay jugadores que coincidan con la búsqueda.":"No hay salidas creadas para este torneo."}</div>`;}
function renderFilter(){const valid=state.viewFilter==="all"||state.blocks.some(block=>block.id===state.viewFilter);if(!valid)state.viewFilter="all";dom.tabs.innerHTML=`<button class="filter-tab ${state.viewFilter==="all"?"active":""}" data-grid-filter="all">Todos</button>`+state.blocks.map(block=>`<button class="filter-tab ${state.viewFilter===block.id?"active":""}" data-grid-filter="${block.id}">${escapeHtml(screenBlockTitle(block))}</button>`).join("");}
function renderSelection(){const needed=requiresPartner()?2:1;dom.summary.innerHTML=state.selected.map((p,i)=>`<div class="selected-player"><span><strong>${i+1}. ${escapeHtml(p.full_name||`${p.last_name}, ${p.first_name}`)}</strong><small>${p.aag_member_number?`Matrícula ${escapeHtml(p.aag_member_number)}`:"Manual"}</small></span><button class="btn secondary small" data-remove-player="${p.id}">Quitar</button></div>`).join("");dom.save.disabled=state.selected.length!==needed;dom.save.textContent=requiresPartner()?`Guardar pareja (${state.selected.length}/2)`:"Guardar inscripción";}

function shortPlayerName(name){const parts=String(name||"").split(",");if(parts.length<2)return String(name||"");return`${parts[0].trim()}, ${parts[1].trim().split(/\s+/).filter(Boolean).map(n=>`${n[0]?.toUpperCase()||""}.`).join(" ")}`}
function addMinutes(time,amount){const [h,m]=String(time||"").slice(0,5).split(":").map(Number);if(!Number.isFinite(h)||!Number.isFinite(m))return"—";const total=(h*60+m+amount)%(24*60);return`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
function exportSlotCell(slot){if(!slot||isEmpty(slot))return'<td class="share-empty"></td>';if(slot.participant_type==="blocked")return'<td class="share-blocked">BLOQUEADO</td>';if(isReservation(slot))return'<td class="share-reserved">RESERVADO</td>';return`<td class="share-player ${slotKind(slot)}">${escapeHtml(shortPlayerName(slot.display_name))}</td>`}
function shareTimeMinutes(time){const[h,m]=String(time||"").slice(0,5).split(":").map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null}
function shareShiftBreak(lines){
  if(lines.length<2)return-1;
  const gaps=[];
  for(let i=1;i<lines.length;i++){const before=shareTimeMinutes(lines[i-1].line_time),after=shareTimeMinutes(lines[i].line_time);if(before!==null&&after!==null&&after>before)gaps.push({index:i,value:after-before,before,after})}
  if(!gaps.length)return-1;
  const normal=Math.min(...gaps.map(g=>g.value)),largest=gaps.reduce((best,gap)=>gap.value>best.value?gap:best,gaps[0]);
  if(largest.value>normal)return largest.index;
  const afternoon=gaps.find(gap=>gap.before<13*60&&gap.after>=13*60);
  return afternoon?.index??-1;
}
function renderShareGrid(){
  const sequential=state.tournament?.start_type!=="simultanea",holes=Number(state.tournament?.hole_count||18),showPass=sequential&&holes===18,showFinish=sequential,columns=5+Number(showPass)+Number(showFinish);
  let rows="";
  for(const block of [...state.blocks].sort((a,b)=>(a.display_order||0)-(b.display_order||0))){
    const lines=blockLines(block.id);
    if(!lines.length)continue;
    const startHole=Number(lines[0]?.starting_hole||0),sectionTitle=sequential?`SALIDA POR HOYO ${startHole}`:`SALIDA ${String(block.start_time||lines[0]?.line_time||"").slice(0,5)}`,shiftBreak=sequential?shareShiftBreak(lines):-1;
    rows+=`<tr class="share-section"><td colspan="${columns}">${escapeHtml(sectionTitle)}</td></tr>`;
    lines.forEach((line,index)=>{
      if(index===shiftBreak)rows+=`<tr class="share-shift-divider"><td colspan="${columns}"></td></tr>`;
      const hole=Number(line.starting_hole||0),slots=new Map(byLine(line.id).map(slot=>[Number(slot.slot_number),slot])),reference=sequential?String(line.line_time||"").slice(0,5):`HOYO ${hole}${/BIS/i.test(line.label||"")?" BIS":""}`;
      rows+=`<tr><td class="share-reference">${escapeHtml(reference)}</td>${[1,2,3,4].map(number=>exportSlotCell(slots.get(number))).join("")}${showPass?`<td class="share-extra">${addMinutes(line.line_time,150)}</td>`:""}${showFinish?`<td class="share-extra">${addMinutes(line.line_time,holes===18?300:150)}</td>`:""}</tr>`;
    });
  }
  const timeColumns=`${showPass?'<col class="share-col-extra">':""}${showFinish?'<col class="share-col-extra">':""}`;
  return`<section class="share-sheet"><header class="share-header"><img src="escudo.png" alt=""><div><div class="share-club">VILLA MARÍA GOLF CLUB</div><h1>${escapeHtml(state.tournament?.name||"TORNEO")}</h1><p>${formatDate(state.tournament?.tournament_date)} · ${escapeHtml(state.tournament?.game_modes?.name||"")} · ${holes} HOYOS · ${state.tournament?.start_type==="simultanea"?"SALIDA SIMULTÁNEA":"SALIDA SECUENCIAL"}</p></div></header><div class="share-rule"></div><table><colgroup><col class="share-col-reference${sequential?"":" shotgun"}"><col span="4" class="share-col-player">${timeColumns}</colgroup><tbody>${rows}</tbody></table><footer><span><i class="share-legend member"></i>Socio VMGC</span><span><i class="share-legend visitor"></i>Invitado AAG</span><span><i class="share-legend manual"></i>Jugador manual</span><strong>Planilla actualizada</strong></footer></section>`;
}
async function exportGridImage(){const button=$("#exportGridButton"),wrap=$("#shareExportWrap");if(!button||!wrap||!state.tournament)return;const original=button.textContent;try{setBusy(button,true,"Generando imagen…");if(typeof window.html2canvas!=="function")throw new Error("No se pudo cargar el generador de imágenes.");wrap.innerHTML=renderShareGrid();const node=wrap.firstElementChild;await Promise.all([...node.querySelectorAll("img")].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=img.onerror=resolve})));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const ios=/iPad|iPhone|iPod/.test(navigator.userAgent),canvas=await window.html2canvas(node,{backgroundColor:"#ffffff",scale:ios?1.25:2,useCORS:true,logging:false,windowWidth:node.scrollWidth,windowHeight:node.scrollHeight});const blob=await new Promise((resolve,reject)=>canvas.toBlob(result=>result?resolve(result):reject(new Error("No se pudo generar la imagen PNG.")),"image/png"));const base=String(state.tournament.name||"grilla").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").toLowerCase()||"grilla",file=new File([blob],`${base}.png`,{type:"image/png"}),mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia("(pointer: coarse)").matches;if(mobile&&navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:`Grilla ${state.tournament.name}`,text:"Planilla actualizada ⛳"});return}catch(error){if(error?.name==="AbortError")return}}const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=file.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(error){notify(error.message||"No se pudo generar la imagen.","error")}finally{setBusy(button,false);button.textContent=original}}

async function reload({quiet=false}={}){if(!state.tournament||state.loading)return;state.loading=true;if(!quiet)dom.grid.classList.add("busy-cover");try{const data=await loadGrid(state.tournament.id,isAdmin);Object.assign(state,data);renderStrip();renderFilter();renderGrid();setActiveTournament(state.tournament);}catch(error){showState(dom.page,`No se pudo cargar la grilla: ${error.message}`,"error");}finally{state.loading=false;dom.grid.classList.remove("busy-cover");}}
async function chooseTournament(id){state.tournament=state.tournaments.find(t=>t.id===id);if(!state.tournament)return;history.replaceState(null,"",`?torneo_id=${encodeURIComponent(id)}`);state.unsubscribe?.();state.unsubscribe=subscribeGrid(id,()=>reload({quiet:true}));await reload();}

async function openFree(slot){if(!canEdit())return notify("El torneo está en modo solo lectura.","error");try{await validateSlotChoice(slot.id,requiresPartner());}catch(error){notify(error.message,"error");return}state.activeSlot=slot;state.selected=[];renderSelection();dom.results.innerHTML='<div class="empty-state compact">Escribí al menos dos caracteres.</div>';dom.search.value="";$("#drawerHint").textContent=requiresPartner()?"Elegí dos jugadores; se ocupará el bloque completo de pareja.":"Elegí el participante para este lugar.";$("#drawerTitle").textContent=requiresPartner()?"Anotar pareja":"Anotar jugador";dom.manual.hidden=!isAdmin;$("#blockEmptyButton").hidden=!isAdmin;try{await lockLine(slot.id,state.member?.id);dom.drawer.classList.add("open");dom.drawer.setAttribute("aria-hidden","false");setTimeout(()=>dom.search.focus(),50);}catch(error){notify(error.message,"error");await reload({quiet:true});}}
async function closePlayerDrawer(){dom.drawer.classList.remove("open");dom.drawer.setAttribute("aria-hidden","true");if(state.activeSlot)await unlockLine(state.activeSlot.id).catch(console.warn);state.activeSlot=null;state.selected=[];}
function openOccupied(slot){state.activeSlot=slot;$("#slotPlayerName").textContent=slot.participant_type==="blocked"?"Lugar bloqueado":isReservation(slot)?"Lugar reservado":slot.display_name;$("#slotPlayerMeta").textContent=slot.aag_member_number?`Matrícula ${slot.aag_member_number}`:(slot.club_name||"");$("#slotDetail").innerHTML=`<div class="slot-detail-row"><span>Club</span><strong>${escapeHtml(slot.club_name||"—")}</strong></div><div class="slot-detail-row"><span>Índice informado</span><strong>${slot.manual_index??"—"}</strong></div><div class="slot-detail-row"><span>Estado</span><strong>${slot.participant_type==="blocked"?"Bloqueado":isReservation(slot)?"Reservado":"Inscripto"}</strong></div>`;$("#releaseButton").hidden=!isOwn(slot);$("#moveButton").hidden=!isAdmin||slot.participant_type==="blocked"||isReservation(slot);$("#blockButton").hidden=!isAdmin||slot.participant_type!=="blocked";if($("#whatsappButton"))$("#whatsappButton").hidden=true;dom.slotDrawer.classList.add("open");}
function closeSlot(){dom.slotDrawer.classList.remove("open");state.activeSlot=null;}

dom.grid.addEventListener("click",async event=>{const button=event.target.closest("[data-slot]");if(!button)return;const slot=state.slots.find(s=>s.id===button.dataset.slot);if(!slot)return;if(state.moveSource){if(!isEmpty(slot))return notify("Elegí un casillero libre como destino.","error");try{await moveRegistration(state.moveSource.id,slot.id,{requiresPartner:requiresPartner()});state.moveSource=null;await reload({quiet:true});notify("Jugador movido correctamente.");}catch(error){notify(error.message,"error");}return}if(isEmpty(slot)){dom.grid.classList.remove("slot-pick-mode");$("#gridInstruction").hidden=true;openFree(slot)}else openOccupied(slot);});
dom.search.addEventListener("input",()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(async()=>{const term=dom.search.value.trim();if(term.length<2){dom.results.innerHTML='<div class="empty-state compact">Escribí al menos dos caracteres.</div>';return;}dom.results.innerHTML='<div class="empty-state compact">Buscando…</div>';try{const players=await searchPlayers(term);dom.results.innerHTML=players.map(p=>`<button class="search-result" data-player='${escapeHtml(JSON.stringify(p))}'><span class="player-avatar">${escapeHtml((p.last_name||p.first_name||"J").slice(0,2).toUpperCase())}</span><span class="copy"><strong>${escapeHtml(p.full_name||`${p.last_name}, ${p.first_name}`)}</strong><small>${p.aag_member_number?`Matrícula ${escapeHtml(p.aag_member_number)}`:"Sin matrícula"} · Índice ${p.current_index??"—"} · ${escapeHtml(p.club_name||"Sin club")}</small></span><span class="source-pill">${p.source_table==="players"?"Local":"AAG"}</span></button>`).join("")||'<div class="empty-state compact">No se encontraron jugadores.</div>';}catch(error){dom.results.innerHTML=`<div class="notice warn">${escapeHtml(error.message)}</div>`;}},280);});
dom.results.addEventListener("click",async event=>{const button=event.target.closest("[data-player]");if(!button)return;try{const raw=JSON.parse(button.dataset.player);const player=await ensurePlayer(raw);if(state.selected.some(p=>p.id===player.id))return notify("Ese jugador ya fue elegido.","error");if(state.selected.length>=(requiresPartner()?2:1))state.selected=[];state.selected.push(player);renderSelection();}catch(error){notify(error.message,"error");}});
dom.summary.addEventListener("click",event=>{const button=event.target.closest("[data-remove-player]");if(!button)return;state.selected=state.selected.filter(p=>String(p.id)!==button.dataset.removePlayer);renderSelection();});
$("#manualForm").addEventListener("submit",async event=>{event.preventDefault();try{const player=await createManualPlayer({firstName:$("#manualFirst").value,lastName:$("#manualLast").value,index:$("#manualIndex").value,gender:$("#manualGender").value,country:$("#manualCountry").value});state.selected.push(player);renderSelection();event.target.reset();$("#manualCountry").value="Argentina";}catch(error){notify(error.message,"error");}});
dom.save.addEventListener("click",async()=>{setBusy(dom.save,true,"Guardando…");try{await registerPlayers({tournamentId:state.tournament.id,slotId:state.activeSlot.id,players:state.selected,isAdmin,memberPlayerId:state.member?.id,requiresPartner:requiresPartner()});await closePlayerDrawer();await reload({quiet:true});notify("Inscripción guardada.");}catch(error){notify(error.code==="23505"?"El jugador o el lugar ya fueron registrados.":error.message,"error");await reload({quiet:true});}finally{setBusy(dom.save,false);renderSelection();}});
dom.reserve.addEventListener("click",async()=>{try{await reserveSlot(state.activeSlot.id,{isAdmin,memberPlayerId:state.member?.id});await closePlayerDrawer();await reload({quiet:true});notify("Lugar reservado.");}catch(error){notify(error.message,"error");}});
$("#blockEmptyButton").addEventListener("click",async()=>{try{await blockSlot(state.activeSlot.id,true);await closePlayerDrawer();await reload({quiet:true});notify("Casillero bloqueado.");}catch(error){notify(error.message,"error");}});
$("#moveButton").addEventListener("click",()=>{state.moveSource=state.activeSlot;closeSlot();notify("Ahora seleccioná el casillero libre de destino.");});
$("#releaseButton").addEventListener("click",async()=>{const slot=state.activeSlot;if(!slot)return;const ok=await confirmAction({title:"Liberar lugar",message:`¿Querés liberar el lugar de ${slot.display_name||"esta reserva"}?`,confirmText:"Liberar",danger:true});if(!ok)return;try{await releaseSlot(slot.id,{isAdmin,memberPlayerId:state.member?.id,tournamentDate:state.tournament.tournament_date,requiresPartner:requiresPartner()});closeSlot();await reload({quiet:true});notify("Lugar liberado.");}catch(error){notify(error.message,"error");if(!isAdmin&&/WhatsApp/.test(error.message))if($("#whatsappButton"))$("#whatsappButton").hidden=false;}});
$("#blockButton").addEventListener("click",async()=>{try{await blockSlot(state.activeSlot.id,false);closeSlot();await reload({quiet:true});notify("Lugar desbloqueado.");}catch(error){notify(error.message,"error");}});
$("#closeDrawer").addEventListener("click",closePlayerDrawer);$("#closeSlotDrawer").addEventListener("click",closeSlot);dom.tabs.addEventListener("click",event=>{const button=event.target.closest("[data-grid-filter]");if(!button)return;state.viewFilter=button.dataset.gridFilter;renderFilter();renderGrid();});dom.gridSearch.addEventListener("input",renderGrid);$("#addPlayerButton").addEventListener("click",()=>{const instruction=$("#gridInstruction");instruction.hidden=false;dom.grid.classList.add("slot-pick-mode");instruction.scrollIntoView({behavior:"smooth",block:"center"});});$("#refreshButton").addEventListener("click",()=>reload());$("#exportGridButton")?.addEventListener("click",exportGridImage);window.addEventListener("beforeunload",()=>state.unsubscribe?.());

try{state.member=isAdmin?null:await getMemberPlayer(context.user.id);if(!isAdmin&&!state.member)throw new Error("Tu usuario no está vinculado con un jugador.");state.tournaments=await listAvailableTournaments(isAdmin);const requested=new URLSearchParams(location.search).get("torneo_id")||getActiveTournament().id;const initial=state.tournaments.find(t=>t.id===requested);if(initial)await chooseTournament(initial.id);else{dom.grid.innerHTML='<div class="empty-state">Elegí el torneo desde el Panel para administrar sus inscripciones.<br><br><a class="btn primary" href="panel_beta.html">Ir al Panel</a></div>';dom.strip.hidden=true;}}
catch(error){showState(dom.page,error.message,"error");dom.grid.innerHTML='<div class="empty-state">No se pudo iniciar la grilla.</div>';}
