import { requireSession } from "./auth_beta.js";
import { mountShell, getActiveTournament, setActiveTournament, captureTournamentFromUrl } from "./shell_beta.js";
import { loadTournamentCatalogs, listManagedTournaments, getTournamentForEdit, saveTournament, deleteTournament, reopenTournament, setTournamentRegistrationStatus, saveCategory } from "./tournament_service_beta.js";
import { escapeHtml, formatDate, setBusy, showState, notify, confirmAction } from "./ui_beta.js";

const context=await requireSession({admin:true});mountShell({context,activeStep:0});
const form=document.getElementById("tournamentForm"),pageState=document.getElementById("pageState"),saveButton=document.getElementById("saveButton"),saveTop=document.getElementById("saveTop");
let catalogs=null,tournaments=[],editingId="",editingStatus="",bis=[new Set(),new Set()],categoryFocusId="",categoryEditingId="";
const byId=id=>document.getElementById(id),value=id=>byId(id).value,setValue=(id,v)=>byId(id).value=v??"";
const switchValue=id=>byId(id).classList.contains("on");
function setSwitch(id,on){const el=byId(id);el.classList.toggle("on",!!on);el.setAttribute("aria-checked",String(!!on))}
const statusLabel=s=>({draft:"Borrador",closed:"Programado",open:"Abierto",officialized:"Guardado",archived:"Archivado"})[s]||s;
function medalModeId(){return catalogs?.gameModes.find(m=>/medal/i.test(m.name||""))?.id||catalogs?.gameModes[0]?.id||""}
function allowedHoles(){return value("segment")==="front9"?Array.from({length:9},(_,i)=>i+1):value("segment")==="back9"?Array.from({length:9},(_,i)=>i+10):Array.from({length:18},(_,i)=>i+1)}
function renderBis(){const allowed=new Set(allowedHoles());byId("bisGrid").innerHTML=Array.from({length:18},(_,i)=>{const h=i+1,enabled=allowed.has(h),m=bis[0].has(h)&&bis[1].has(h)?2:bis[0].has(h)?1:bis[1].has(h)?3:0;return`<button class="bis-hole" type="button" data-hole="${h}" data-mode="${m}" ${enabled?"":"disabled"} title="${enabled?(m===1?'Horario 1':m===2?'Ambos horarios':m===3?'Horario 2':'Sin BIS'):'Hoyo fuera del segmento seleccionado'}">${h}${enabled&&m===1?' · 1':enabled&&m===2?' · 1+2':enabled&&m===3?' · 2':''}</button>`}).join("");byId("bisGrid").querySelectorAll("button:not(:disabled)").forEach(btn=>btn.addEventListener("click",()=>{const h=Number(btn.dataset.hole),m=(Number(btn.dataset.mode)+1)%4;bis[0].delete(h);bis[1].delete(h);if(m===1||m===2)bis[0].add(h);if(m===2||m===3)bis[1].add(h);renderBis()}))}
function updateSegment(){const segment=value("segment"),frontDisabled=segment==="back9",backDisabled=segment==="front9";["b1amStart","b1amEnd","b1pmStart","b1pmEnd"].forEach(id=>{byId(id).disabled=frontDisabled;byId(id).closest(".field")?.classList.toggle("field-disabled",frontDisabled)});["b2amStart","b2amEnd","b2pmStart","b2pmEnd"].forEach(id=>{byId(id).disabled=backDisabled;byId(id).closest(".field")?.classList.toggle("field-disabled",backDisabled)});const allowed=new Set(allowedHoles());bis=bis.map(set=>new Set([...set].filter(h=>allowed.has(h))));renderBis()}
function updateStartType(){const shotgun=value("startType")==="simultanea";byId("sequentialConfig").hidden=shotgun;byId("shotgunConfig").hidden=!shotgun}
function updateSeries(){const type=value("seriesType");document.querySelectorAll("[data-series-existing]").forEach(x=>x.hidden=type!=="existing");document.querySelectorAll("[data-series-new]").forEach(x=>x.hidden=type!=="new");document.querySelectorAll("[data-series-round]").forEach(x=>x.hidden=type==="none");if(type==="existing"){const option=byId("seriesId").selectedOptions[0];if(option?.dataset.scoring)setSwitch("grossSwitch",option.dataset.scoring==="gross")}}
function updateGross(){const mode=catalogs?.gameModes.find(m=>m.id===value("gameMode")),medal=/medal/i.test(mode?.name||"");if(!medal)setSwitch("grossSwitch",false);byId("grossSwitch").style.opacity=medal?"1":".45";byId("grossSwitch").style.pointerEvents=medal?"auto":"none"}
function updateCategorySummary(){const checked=[...byId("categoryGrid").querySelectorAll("input:checked")];byId("categorySummary").textContent=`${checked.length} ${checked.length===1?"seleccionada":"seleccionadas"}`}
function renderCategories(selected){const chosen=new Set(selected||[]);byId("categoryGrid").innerHTML=catalogs.categories.map((c,i)=>`<label class="choice ${c.id===categoryFocusId?'focused':''}" data-category="${c.id}"><input type="checkbox" value="${c.id}" ${chosen.has(c.id)||(!editingId&&!selected&&i<5)?"checked":""} ${c.valid?"":"disabled"}><span><b>${escapeHtml(c.name)}</b><small>${c.playing_handicap_min??"–"} a ${c.playing_handicap_max??"–"} HCP · ${c.valid?"Tees AAG vigentes":"Requiere revisión"}</small></span></label>`).join("");byId("categoryGrid").querySelectorAll(".choice").forEach(label=>label.addEventListener("click",()=>{categoryFocusId=label.dataset.category;byId("categoryGrid").querySelectorAll(".choice").forEach(x=>x.classList.toggle("focused",x.dataset.category===categoryFocusId));queueMicrotask(updateCategorySummary)}));updateCategorySummary()}
function renderList(){}
function toMinutes(t){const[h,m]=String(t).split(":").map(Number);return h*60+m}
function rangeFromLines(lines){const times=[...new Set(lines.map(l=>String(l.line_time||"").slice(0,5)))].sort();if(!times.length)return{am:[],pm:[]};let cut=-1;for(let i=1;i<times.length;i++)if(toMinutes(times[i])-toMinutes(times[i-1])>Number(value("interval")||10)){cut=i;break}return cut<0?{am:times,pm:[]}:{am:times.slice(0,cut),pm:times.slice(cut)}}
function setRange(prefix,range){setValue(prefix+"Start",range[0]||"");setValue(prefix+"End",range.at(-1)||"")}
function updateStatusButton(){const button=byId("statusButton"),current=tournaments.find(t=>t.id===editingId);if(!editingId||!current?.status||current.aag_exported){button.hidden=true;return}if(current.status==="archived"){button.hidden=false;button.textContent="Reabrir torneo";return}if(["open","closed"].includes(current.status)){button.hidden=false;button.textContent=current.status==="open"?"Cerrar inscripciones":"Abrir inscripciones";return}button.hidden=true}
function renderActiveOverview(t){const categories=(t.tournament_categories||[]).filter(c=>c.category_system==="new"),blocks=t.starting_blocks||[],published=t.published!==false;byId("configTournamentStrip").innerHTML=`<section class="tournament-strip"><div class="tournament-main"><span class="status ${t.status==="open"?"open":"pending"}">${escapeHtml(statusLabel(t.status))}</span><h2>${escapeHtml(t.name)}</h2><div class="meta">${formatDate(t.tournament_date)} · ${escapeHtml(t.game_modes?.name||"")} · V2</div></div><div class="metric"><strong>${categories.length}</strong><span>Categorías</span></div><div class="metric"><strong>${blocks.length}</strong><span>Salidas</span></div><div class="metric"><strong>${published?"Visible":"Oculto"}</strong><span>Publicación</span></div><div class="metric"><strong>${t.start_type==="simultanea"?"Simultánea":"Secuencial"}</strong><span>Formato</span></div></section>`;byId("configSummary").innerHTML=`<div class="timeline-item"><div class="timeline-mark"><i>1</i></div><div class="timeline-copy"><strong>Datos principales</strong><span>${escapeHtml(t.name)} · ${formatDate(t.tournament_date)}</span></div></div><div class="timeline-item"><div class="timeline-mark"><i>2</i></div><div class="timeline-copy"><strong>Categorías</strong><span>${categories.length} seleccionadas</span></div></div><div class="timeline-item"><div class="timeline-mark"><i>3</i></div><div class="timeline-copy"><strong>Salidas</strong><span>${blocks.length} configuradas · ${t.start_type==="simultanea"?"simultánea":"secuencial"}</span></div></div>`;byId("goRegistrations").href=`inscripciones_beta.html?torneo_id=${encodeURIComponent(t.id)}`}
function resetForm(){editingId="";editingStatus="";form.reset();setValue("gameMode",medalModeId());setValue("interval",10);setValue("segment","18");setValue("startType","secuencial");setValue("seriesType","none");setSwitch("hiddenSwitch",false);setSwitch("grossSwitch",false);bis=[new Set(),new Set()];categoryFocusId="";updateSegment();renderCategories();byId("editionBadge").textContent="Nuevo V2";byId("deleteButton").hidden=true;updateStatusButton();byId("categoriesDetails").open=false;updateStartType();updateSeries();updateGross();byId("configTournamentStrip").innerHTML="";byId("configSummary").innerHTML='<div class="notice">Completá los datos para crear el torneo.</div>';byId("goRegistrations").href="inscripciones_beta.html";history.replaceState({},"",location.pathname+"?nuevo=1")}
async function loadEdit(id){try{showState(pageState,"Cargando torneo...","info");const t=await getTournamentForEdit(id);editingId=t.id;editingStatus=t.status;setActiveTournament(t);setValue("name",t.name);setValue("date",t.tournament_date);setValue("gameMode",t.game_mode_id);setValue("segment",t.tournament_categories?.[0]?.hole_segment||(Number(t.hole_count)===9?"front9":"18"));setValue("startType",t.start_type||"secuencial");setSwitch("hiddenSwitch",!t.published);setSwitch("grossSwitch",t.scoring_mode==="gross");setValue("seriesType",t.series_id?"existing":"none");setValue("seriesId",t.series_id);setValue("seriesRound",t.series_round_number);renderCategories((t.tournament_categories||[]).filter(c=>c.category_system==="new").map(c=>c.category_id));bis=[new Set(),new Set()];const blocks=[...(t.starting_blocks||[])].sort((a,b)=>(a.display_order||0)-(b.display_order||0));if(t.start_type==="simultanea"){setValue("shotgun1",String(blocks[0]?.start_time||"").slice(0,5));setValue("shotgun2",String(blocks[1]?.start_time||"").slice(0,5));blocks.slice(0,2).forEach((b,i)=>(b.starting_lines||[]).filter(l=>String(l.label||"").includes("BIS")).forEach(l=>bis[i].add(Number(l.starting_hole))))}else{const frontBlock=blocks.find(b=>/^bloque\s*1$/i.test(String(b.name||"").trim())),backBlock=blocks.find(b=>/^bloque\s*2$/i.test(String(b.name||"").trim())),r1=rangeFromLines(frontBlock?.starting_lines||[]),r2=rangeFromLines(backBlock?.starting_lines||[]);setRange("b1am",r1.am);setRange("b1pm",r1.pm);setRange("b2am",r2.am);setRange("b2pm",r2.pm)}updateSegment();updateStartType();updateSeries();updateGross();byId("editionBadge").textContent=`Editando · ${statusLabel(t.status)}`;const current=tournaments.find(item=>item.id===t.id);byId("deleteButton").hidden=!!current?.aag_exported;updateStatusButton();renderActiveOverview(t);pageState.hidden=true;history.replaceState({},"",`?torneo_id=${encodeURIComponent(id)}`);scrollTo({top:0,behavior:"smooth"})}catch(error){showState(pageState,error.message,"error")}}
function getInput(){return{id:editingId||null,name:value("name"),date:value("date"),gameModeId:value("gameMode"),segment:value("segment"),startType:value("startType"),published:!switchValue("hiddenSwitch"),scoringMode:switchValue("grossSwitch")?"gross":"net",categoryIds:[...byId("categoryGrid").querySelectorAll("input:checked")].map(x=>x.value),interval:Number(value("interval")||10),sequential:{b1am:{start:value("b1amStart"),end:value("b1amEnd")},b1pm:{start:value("b1pmStart"),end:value("b1pmEnd")},b2am:{start:value("b2amStart"),end:value("b2amEnd")},b2pm:{start:value("b2pmStart"),end:value("b2pmEnd")}},simultaneous:[value("shotgun1"),value("shotgun2")],bis:[...bis].map(set=>[...set]),series:{type:value("seriesType"),id:value("seriesId"),name:value("seriesName"),requiredRounds:Number(value("seriesRounds")||0),round:Number(value("seriesRound")||0)}}}
async function save(event){event.preventDefault();try{pageState.hidden=true;setBusy(saveButton,true,editingId?"Actualizando...":"Creando...");saveTop.disabled=true;const input=getInput(),id=await saveTournament(input,catalogs);setActiveTournament({id,name:input.name.trim().toUpperCase()});notify(editingId?"Torneo actualizado":"Torneo creado");tournaments=await listManagedTournaments();await loadEdit(id)}catch(error){showState(pageState,error.message||"No se pudo guardar el torneo.","error");scrollTo({top:0,behavior:"smooth"})}finally{setBusy(saveButton,false);saveTop.disabled=false}}
async function removeTournament(id){if(!id)return;const current=tournaments.find(t=>t.id===id),ok=await confirmAction({title:"Eliminar torneo",message:`Se eliminará completamente “${current?.name||"este torneo"}”. Sólo continuará si no tiene inscriptos.`,confirmText:"Eliminar",danger:true});if(!ok)return;try{await deleteTournament(id);notify("Torneo eliminado.");location.href="panel_beta.html"}catch(error){showState(pageState,error.message,"error")}}
async function reopen(id){const t=tournaments.find(x=>x.id===id),ok=await confirmAction({title:"Reabrir torneo",message:`“${t?.name||"Este torneo"}” volverá al estado Abierto para modificar inscriptos y cargar tarjetas.`,confirmText:"Reabrir"});if(!ok)return;try{await reopenTournament(id);notify("Torneo reabierto.");tournaments=await listManagedTournaments();renderList();await loadEdit(id)}catch(error){showState(pageState,error.message,"error")}}
async function toggleRegistrationStatus(id){const tournament=tournaments.find(t=>t.id===id);if(!tournament||!["open","closed"].includes(tournament.status))return;const next=tournament.status==="open"?"closed":"open",verb=next==="open"?"abrir":"cerrar",ok=await confirmAction({title:`${next==="open"?"Abrir":"Cerrar"} inscripciones`,message:`¿Querés ${verb} las inscripciones de “${tournament.name}”?`,confirmText:next==="open"?"Abrir":"Cerrar"});if(!ok)return;try{await setTournamentRegistrationStatus(id,next);tournaments=await listManagedTournaments();await loadEdit(id);notify(next==="open"?"Inscripciones abiertas.":"Inscripciones cerradas.")}catch(error){showState(pageState,error.message,"error")}}

function teeOptions(selected=""){return '<option value="">Seleccionar tee AAG…</option>'+catalogs.tees.map(t=>`<option value="${t.id}" ${String(t.id)===String(selected)?"selected":""}>${escapeHtml(`${t.tee_name||"Tee"} · ${t.category||""}`)}</option>`).join("")}
function addRule(rule={}){const row=document.createElement("div");row.className="category-rule";row.innerHTML=`<select class="control rule-tee">${teeOptions(rule.aag_teeout_id)}</select><input class="control rule-min" type="number" step="0.1" placeholder="Índice mín." value="${rule.index_min??""}"><input class="control rule-max" type="number" step="0.1" placeholder="Índice máx." value="${rule.index_max??""}"><button class="btn danger small" type="button">Quitar</button>`;row.querySelector("button").addEventListener("click",()=>row.remove());row.querySelector("select").addEventListener("change",updatePlayingTeeOptions);byId("categoryRules").appendChild(row);updatePlayingTeeOptions()}
function updatePlayingTeeOptions(selected){const current=selected!==undefined?String(selected):value("categoryPlayingTee"),ids=[...byId("categoryRules").querySelectorAll(".rule-tee")].map(x=>x.value).filter(Boolean);byId("categoryPlayingTee").innerHTML='<option value="">Sin tee obligatorio</option>'+ids.map(id=>{const tee=catalogs.tees.find(t=>String(t.id)===id);return`<option value="${id}" ${id===current?"selected":""}>${escapeHtml(tee?.tee_name||"Tee")}</option>`}).join("")}
function openCategory(category=null){categoryEditingId=category?.id||"";byId("categoryDrawerTitle").textContent=category?`Modificar ${category.name}`:"Nueva categoría";setValue("categoryName",category?.name);setValue("categoryHcpMin",category?.playing_handicap_min);setValue("categoryHcpMax",category?.playing_handicap_max);setValue("categoryOrder",category?.display_order??Math.max(0,...catalogs.categories.map(c=>Number(c.display_order)||0))+1);byId("categoryRules").innerHTML="";(category?.tee_rules?.length?category.tee_rules:[{}]).forEach(addRule);updatePlayingTeeOptions(category?.playing_tee_aag_teeout_id);byId("categoryMessage").hidden=true;byId("categoryDrawer").classList.add("open")}
function closeCategory(){byId("categoryDrawer").classList.remove("open")}
async function submitCategory(event){event.preventDefault();const button=byId("saveCategoryButton");try{setBusy(button,true,"Guardando…");const rules=[...byId("categoryRules").querySelectorAll(".category-rule")].map(row=>({aag_teeout_id:row.querySelector(".rule-tee").value,index_min:row.querySelector(".rule-min").value,index_max:row.querySelector(".rule-max").value}));await saveCategory({id:categoryEditingId,name:value("categoryName"),playingHandicapMin:value("categoryHcpMin"),playingHandicapMax:value("categoryHcpMax"),displayOrder:value("categoryOrder"),playingTeeId:value("categoryPlayingTee"),rules},catalogs);const selected=[...byId("categoryGrid").querySelectorAll("input:checked")].map(x=>x.value);catalogs=await loadTournamentCatalogs();renderCategories(selected);closeCategory();notify(categoryEditingId?"Categoría actualizada.":"Categoría creada.")}catch(error){showState(byId("categoryMessage"),error.message,"error")}finally{setBusy(button,false)}}

try{catalogs=await loadTournamentCatalogs();tournaments=await listManagedTournaments();byId("gameMode").innerHTML=catalogs.gameModes.map(m=>`<option value="${m.id}">${escapeHtml(m.name)}</option>`).join("");byId("seriesId").innerHTML='<option value="">Seleccionar...</option>'+catalogs.series.map(s=>`<option value="${s.id}" data-scoring="${s.scoring_mode||'net'}">${escapeHtml(s.name)} (${s.required_rounds||'?'} fechas)</option>`).join("");renderCategories();renderBis();const params=new URLSearchParams(location.search),selected=captureTournamentFromUrl(tournaments)||tournaments.find(t=>t.id===getActiveTournament().id);if(params.get("nuevo")==="1")resetForm();else if(selected)await loadEdit(selected.id);else resetForm()}catch(error){showState(pageState,error.message||"No se pudo iniciar la pantalla.","error")}
["hiddenSwitch","grossSwitch"].forEach(id=>byId(id).addEventListener("click",()=>setSwitch(id,!switchValue(id))));byId("startType").addEventListener("change",updateStartType);byId("segment").addEventListener("change",updateSegment);byId("seriesType").addEventListener("change",updateSeries);byId("seriesId").addEventListener("change",updateSeries);byId("gameMode").addEventListener("change",updateGross);byId("resetButton").addEventListener("click",resetForm);byId("statusButton").addEventListener("click",()=>editingStatus==="archived"?reopen(editingId):toggleRegistrationStatus(editingId));byId("deleteButton").addEventListener("click",()=>removeTournament(editingId));form.addEventListener("submit",save);saveTop.addEventListener("click",()=>form.requestSubmit());byId("newCategoryButton").addEventListener("click",()=>openCategory());byId("editCategoryButton").addEventListener("click",()=>{const id=categoryFocusId||byId("categoryGrid").querySelector("input:checked")?.value,category=catalogs.categories.find(c=>c.id===id);if(!category)return notify("Seleccioná una categoría para modificar.","error");openCategory(category)});byId("closeCategoryDrawer").addEventListener("click",closeCategory);byId("addCategoryRule").addEventListener("click",()=>addRule());byId("categoryForm").addEventListener("submit",submitCategory);
