import { requireSession } from "./auth.js";
import { mountShell, getActiveTournament, setActiveTournament, renderStageNavigation } from "./shell.js";
import { escapeHtml, notify, showState, confirmAction, setBusy } from "./ui.js";
import { listAvailableTournaments, loadGrid, getMemberPlayer, searchPlayers, ensurePlayer, createManualPlayer, lockLine, unlockLine, registerPlayers, reserveSlot, releaseSlot, blockSlot, moveRegistration, validateSlotChoice, isEmpty, isReservation, subscribeGrid } from "./registration_service.js";

const context = await requireSession();
const isAdmin = context.profile.role === "admin";
mountShell({context,activeStep:1});

const $ = selector => document.querySelector(selector);
const state = { tournaments:[], tournament:null, blocks:[], lines:[], slots:[], member:null, activeSlot:null, moveSource:null, selected:[], unsubscribe:null, searchTimer:null, loading:false, viewFilter:"all" };
const dom = { page:$("#pageState"),strip:$("#tournamentStrip"),tabs:$("#gridViewTabs"),gridSearch:$("#gridPlayerSearch"),grid:$("#gridHost"),drawer:$("#playerDrawer"),slotDrawer:$("#slotDrawer"),search:$("#playerSearch"),results:$("#searchResults"),summary:$("#selectionSummary"),save:$("#saveRegistration"),reserve:$("#reserveButton"),manual:$("#manualPanel") };
if(isAdmin) $("#whatsappButton")?.remove();
if(isAdmin) $("#exportGridButton").hidden=false; else $("#exportGridButton")?.remove();

const statusLabel = value => ({open:"Inscripción abierta",closed:"Inscripción cerrada",officialized:"Guardado",archived:"Archivado"})[value] || value;
const canEdit = () => isAdmin ? ["open","closed","officialized"].includes(state.tournament?.status) : state.tournament?.status === "open";
const requiresPartner = () => state.tournament?.game_modes?.requires_partner === true;
const byLine = lineId => state.slots.filter(slot => slot.starting_line_id === lineId).sort((a,b)=>a.slot_number-b.slot_number);
const isBisLine = line => /\bBIS\b/i.test(String(line?.label||""));
const blockLines = blockId => state.lines.filter(line => line.starting_block_id === blockId).sort((a,b)=>{
  if(state.tournament?.start_type==="simultanea"){
    const holeDifference=Number(a.starting_hole||0)-Number(b.starting_hole||0);
    if(holeDifference)return holeDifference;
    const bisDifference=Number(isBisLine(a))-Number(isBisLine(b));
    if(bisDifference)return bisDifference;
  }
  return Number(a.display_order||0)-Number(b.display_order||0);
});
const lockOther = slot => slot.lock_expires_at && new Date(slot.lock_expires_at)>new Date() && slot.locked_by_player_id !== state.member?.id && !isReservation(slot);
const isOwn = slot => isAdmin || String(slot.linked_player_id||"")===String(state.member?.id||"") || String(slot.created_by_player_id||"")===String(state.member?.id||"") || String(slot.locked_by_player_id||"")===String(state.member?.id||"") || (!!slot.aag_member_number && String(slot.aag_member_number)===String(state.member?.aag_member_number||""));
const slotKind = slot => { if(slot.participant_type==="blocked")return"blocked";if(isReservation(slot))return"reserved";if(!slot.aag_member_number)return"manual";return Number(slot.option_club_id)===408 || /VILLA MAR[IÍ]A/i.test(slot.club_name||"") ? "member":"visitor"; };
const lineLabel = line => state.tournament?.start_type === "simultanea" ? (line.label || `Hoyo ${line.starting_hole}`) : String(line.line_time||"").slice(0,5);
const lineSub = line => state.tournament?.start_type === "simultanea" ? String(line.line_time||"").slice(0,5) : `Hoyo ${line.starting_hole}`;

function renderStrip(){const occupied=state.slots.filter(s=>!isEmpty(s)&&s.participant_type!=="blocked"&&!isReservation(s)).length;const free=state.slots.filter(isEmpty).length;renderStageNavigation(dom.strip,1,state.tournament.id);const summary=$("#gridSummary");if(summary)summary.textContent=`${occupied} inscriptos · ${free} lugares libres`;}

function slotOrigin(slot){if(slot.participant_type==="admin")return{icon:"◆",label:"Anotado por admin",kind:"admin"};if(slot.participant_type==="self")return{icon:"●",label:"Inscripción propia",kind:"self"};if(slot.participant_type==="guest")return{icon:"＋",label:"Invitado por socio",kind:"guest"};return null;}
function renderSlot(slot){if(slot.participant_type==="blocked")return `<button class="slot blocked" data-slot="${slot.id}"><span class="slot-number">${slot.slot_number}</span><strong>Bloqueado</strong><span>Administración</span></button>`;if(isReservation(slot))return `<button class="slot reserved" data-slot="${slot.id}"><span class="slot-number">${slot.slot_number}</span><strong>Reservado</strong><span>${slot.notes==="RESERVA_ADMIN"?"Por administración":"Por 24 horas"}</span></button>`;if(isEmpty(slot))return `<button class="slot free ${lockOther(slot)?"locked":""}" data-slot="${slot.id}" ${!canEdit()||lockOther(slot)?"disabled":""}><span class="slot-number">${slot.slot_number}</span><strong>${lockOther(slot)?"Seleccionando…":"＋ Agregar"}</strong><span>Lugar libre</span></button>`;const origin=slotOrigin(slot);return `<button class="slot ${slotKind(slot)} ${origin?`origin-${origin.kind}`:""}" data-slot="${slot.id}" title="${escapeHtml(origin?.label||"")}"><span class="slot-number">${slot.slot_number}</span><strong>${escapeHtml(slot.display_name)}</strong><span class="slot-club">${escapeHtml(slot.club_name || (slot.aag_member_number?"AAG":"Jugador manual"))}</span></button>`;}
function screenBlockTitle(block){if(state.tournament?.start_type==="simultanea")return block.name||"Salida simultánea";const firstLine=blockLines(block.id)[0],fallback=/bloque\s*2/i.test(String(block.name||""))?10:1;return`Salida por Hoyo ${Number(firstLine?.starting_hole||fallback)}`}
function lineMatchesSearch(line,query){if(!query)return true;return byLine(line.id).some(slot=>`${slot.display_name||""} ${slot.aag_member_number||""}`.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").includes(query));}
function screenShiftBreak(lines){if(lines.length<2)return-1;const toMinutes=value=>{const[h,m]=String(value||"").slice(0,5).split(":").map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null},gaps=[];for(let index=1;index<lines.length;index++){const before=toMinutes(lines[index-1].line_time),after=toMinutes(lines[index].line_time);if(before!==null&&after!==null&&after>before)gaps.push({index,value:after-before,before,after})}if(!gaps.length)return-1;const normal=Math.min(...gaps.map(gap=>gap.value)),largest=gaps.reduce((best,gap)=>gap.value>best.value?gap:best,gaps[0]);if(largest.value>normal)return largest.index;return gaps.find(gap=>gap.before<13*60&&gap.after>=13*60)?.index??-1}
function renderScreenLines(block,shotgun,query=""){const allLines=blockLines(block.id),lines=query?allLines.filter(line=>lineMatchesSearch(line,query)):allLines,shiftBreak=shotgun||query?-1:screenShiftBreak(lines);return lines.map((line,index)=>`${index===shiftBreak?'<div class="screen-shift-divider"><span>Turno tarde</span></div>':""}<div class="slot-line ${shotgun?"shotgun":""}"><div class="slot-time">${escapeHtml(lineLabel(line))}<small class="line-label">${escapeHtml(lineSub(line))}</small></div>${byLine(line.id).map(renderSlot).join("")}</div>`).join("")}
function blockMatchesSearch(block,query){return !query||blockLines(block.id).some(line=>lineMatchesSearch(line,query));}
function renderGrid(){const shotgun=state.tournament?.start_type==="simultanea",query=(dom.gridSearch?.value||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""),blocks=state.blocks.filter(block=>(state.viewFilter==="all"||block.id===state.viewFilter)&&blockMatchesSearch(block,query));dom.grid.innerHTML=blocks.map(block=>`<article class="grid-block"><header class="grid-block-head"><div><h2>${escapeHtml(screenBlockTitle(block))}</h2><div class="subtle">${escapeHtml(String(block.start_time||"").slice(0,5))}</div></div><span class="status neutral">${query?"Coincidencia":`${blockLines(block.id).length} líneas`}</span></header><div class="grid-block-body">${renderScreenLines(block,shotgun,query)||'<div class="empty-state">Este bloque no tiene coincidencias.</div>'}</div></article>`).join("")||`<div class="empty-state">${query?"No hay jugadores que coincidan con la búsqueda.":"No hay salidas creadas para este torneo."}</div>`;}
function renderFilter(){const valid=state.viewFilter==="all"||state.blocks.some(block=>block.id===state.viewFilter);if(!valid)state.viewFilter="all";dom.tabs.innerHTML=`<button class="filter-tab ${state.viewFilter==="all"?"active":""}" data-grid-filter="all">Todos</button>`+state.blocks.map(block=>`<button class="filter-tab ${state.viewFilter===block.id?"active":""}" data-grid-filter="${block.id}">${escapeHtml(screenBlockTitle(block))}</button>`).join("");}
function renderSelection(){const needed=requiresPartner()?2:1;dom.summary.innerHTML=state.selected.map((p,i)=>`<div class="selected-player"><span><strong>${i+1}. ${escapeHtml(p.full_name||`${p.last_name}, ${p.first_name}`)}</strong><small>${p.aag_member_number?`Matrícula ${escapeHtml(p.aag_member_number)}`:"Manual"}</small></span><button class="btn secondary small" data-remove-player="${p.id}">Quitar</button></div>`).join("");dom.save.disabled=state.selected.length!==needed;dom.save.textContent=requiresPartner()?`Guardar pareja (${state.selected.length}/2)`:"Guardar inscripción";const blockButton=$("#blockEmptyButton");if(blockButton)blockButton.hidden=!isAdmin||state.selected.length>0;const selfButton=$("#selfRegisterButton"),alreadyRegistered=state.slots.some(slot=>String(slot.linked_player_id||"")===String(state.member?.id||""));if(selfButton)selfButton.hidden=isAdmin||!state.member||alreadyRegistered||state.selected.some(player=>String(player.id)===String(state.member.id));}

async function reload({quiet=false}={}){if(!state.tournament||state.loading)return;state.loading=true;if(!quiet)dom.grid.classList.add("busy-cover");try{const data=await loadGrid(state.tournament.id,isAdmin);Object.assign(state,data);renderStrip();renderFilter();renderGrid();setActiveTournament(state.tournament);}catch(error){showState(dom.page,`No se pudo cargar la grilla: ${error.message}`,"error");}finally{state.loading=false;dom.grid.classList.remove("busy-cover");}}
async function chooseTournament(id){state.tournament=state.tournaments.find(t=>t.id===id);if(!state.tournament)return;history.replaceState(null,"",`?torneo_id=${encodeURIComponent(id)}`);state.unsubscribe?.();state.unsubscribe=subscribeGrid(id,()=>reload({quiet:true}));await reload();}

async function openFree(slot){if(!canEdit())return notify("El torneo está en modo solo lectura.","error");try{await validateSlotChoice(slot.id,requiresPartner());}catch(error){notify(error.message,"error");return}state.activeSlot=slot;state.selected=[];renderSelection();dom.results.innerHTML='<div class="empty-state compact">Escribí al menos dos caracteres.</div>';dom.search.value="";$("#drawerHint").textContent=requiresPartner()?"Elegí dos jugadores; se ocupará el bloque completo de pareja.":"Elegí el participante para este lugar.";$("#drawerTitle").textContent=requiresPartner()?"Anotar pareja":"Anotar jugador";dom.manual.hidden=!isAdmin;$("#blockEmptyButton").hidden=!isAdmin;try{await lockLine(slot.id,state.member?.id);dom.drawer.classList.add("open");dom.drawer.setAttribute("aria-hidden","false");setTimeout(()=>dom.search.focus(),50);}catch(error){notify(error.message,"error");await reload({quiet:true});}}
async function closePlayerDrawer(){dom.drawer.classList.remove("open");dom.drawer.setAttribute("aria-hidden","true");if(state.activeSlot)await unlockLine(state.activeSlot.id).catch(console.warn);state.activeSlot=null;state.selected=[];}
function whatsappWindowOpen(){const [year,month,day]=String(state.tournament?.tournament_date||"").split("-").map(Number);if(!year)return false;const start=new Date(year,month-1,day,0,0,0,0),end=new Date(year,month-1,day+1,0,0,0,0),now=new Date();return now>=new Date(start.getTime()-24*3600000)&&now<end;}
function openOccupied(slot){state.activeSlot=slot;$("#slotPlayerName").textContent=slot.participant_type==="blocked"?"Lugar bloqueado":isReservation(slot)?"Lugar reservado":slot.display_name;$("#slotPlayerMeta").textContent=slot.aag_member_number?`Matrícula ${slot.aag_member_number}`:(slot.club_name||"");const origin=slotOrigin(slot);$("#slotDetail").innerHTML=`<div class="slot-detail-row"><span>Club</span><strong>${escapeHtml(slot.club_name||"—")}</strong></div><div class="slot-detail-row"><span>Índice informado</span><strong>${slot.manual_index??"—"}</strong></div><div class="slot-detail-row"><span>Estado</span><strong>${slot.participant_type==="blocked"?"Bloqueado":isReservation(slot)?"Reservado":"Inscripto"}</strong></div>${origin?`<div class="slot-detail-row"><span>Origen</span><strong>${escapeHtml(origin.label)}</strong></div>`:""}`;$("#releaseButton").hidden=!isOwn(slot);$("#moveButton").hidden=!canEdit()||!isOwn(slot)||slot.participant_type==="blocked"||isReservation(slot);$("#blockButton").hidden=!isAdmin||slot.participant_type!=="blocked";if($("#whatsappButton"))$("#whatsappButton").hidden=isAdmin||!isOwn(slot)||!whatsappWindowOpen();dom.slotDrawer.classList.add("open");}
function closeSlot(){dom.slotDrawer.classList.remove("open");state.activeSlot=null;}

dom.grid.addEventListener("click",async event=>{const button=event.target.closest("[data-slot]");if(!button)return;const slot=state.slots.find(s=>s.id===button.dataset.slot);if(!slot)return;if(state.moveSource){if(!isEmpty(slot))return notify("Elegí un casillero libre como destino.","error");try{await moveRegistration(state.moveSource.id,slot.id,{requiresPartner:requiresPartner(),isAdmin,memberPlayerId:state.member?.id,memberNumber:state.member?.aag_member_number});state.moveSource=null;await reload({quiet:true});notify("Jugador movido correctamente.");}catch(error){notify(error.message,"error");}return}if(isEmpty(slot)){dom.grid.classList.remove("slot-pick-mode");$("#gridInstruction").hidden=true;openFree(slot)}else openOccupied(slot);});
dom.search.addEventListener("input",()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(async()=>{const term=dom.search.value.trim();if(term.length<2){dom.results.innerHTML='<div class="empty-state compact">Escribí al menos dos caracteres.</div>';return;}dom.results.innerHTML='<div class="empty-state compact">Buscando…</div>';try{const players=await searchPlayers(term);dom.results.innerHTML=players.map(p=>`<button class="search-result" data-player='${escapeHtml(JSON.stringify(p))}'><span class="player-avatar">${escapeHtml((p.last_name||p.first_name||"J").slice(0,2).toUpperCase())}</span><span class="copy"><strong>${escapeHtml(p.full_name||`${p.last_name}, ${p.first_name}`)}</strong><small>${p.aag_member_number?`Matrícula ${escapeHtml(p.aag_member_number)}`:"Sin matrícula"} · Índice ${p.current_index??"—"} · ${escapeHtml(p.club_name||"Sin club")}</small></span><span class="source-pill">${p.source_table==="players"?"Local":"AAG"}</span></button>`).join("")||'<div class="empty-state compact">No se encontraron jugadores.</div>';}catch(error){dom.results.innerHTML=`<div class="notice warn">${escapeHtml(error.message)}</div>`;}},280);});
dom.results.addEventListener("click",async event=>{const button=event.target.closest("[data-player]");if(!button)return;try{const raw=JSON.parse(button.dataset.player);const player=await ensurePlayer(raw);if(state.selected.some(p=>p.id===player.id))return notify("Ese jugador ya fue elegido.","error");if(state.selected.length>=(requiresPartner()?2:1))state.selected=[];state.selected.push(player);renderSelection();dom.search.value="";dom.results.innerHTML='<div class="empty-state compact">Jugador seleccionado. Buscá el próximo participante.</div>';dom.search.focus();}catch(error){notify(error.message,"error");}});
$("#selfRegisterButton")?.addEventListener("click",()=>{if(!state.member||state.selected.some(player=>String(player.id)===String(state.member.id)))return;const needed=requiresPartner()?2:1;if(state.selected.length>=needed)state.selected=[];state.selected.push(state.member);renderSelection();dom.search.value="";dom.results.innerHTML='<div class="empty-state compact">Te seleccionaste. Buscá al próximo participante.</div>';dom.search.focus();});
dom.summary.addEventListener("click",event=>{const button=event.target.closest("[data-remove-player]");if(!button)return;state.selected=state.selected.filter(p=>String(p.id)!==button.dataset.removePlayer);renderSelection();});
$("#manualForm").addEventListener("submit",async event=>{event.preventDefault();try{const player=await createManualPlayer({firstName:$("#manualFirst").value,lastName:$("#manualLast").value,index:$("#manualIndex").value,gender:$("#manualGender").value,country:$("#manualCountry").value});state.selected.push(player);renderSelection();event.target.reset();$("#manualCountry").value="Argentina";}catch(error){notify(error.message,"error");}});
dom.save.addEventListener("click",async()=>{setBusy(dom.save,true,"Guardando…");try{await registerPlayers({tournamentId:state.tournament.id,slotId:state.activeSlot.id,players:state.selected,isAdmin,memberPlayerId:state.member?.id,requiresPartner:requiresPartner()});await closePlayerDrawer();await reload({quiet:true});notify("Inscripción guardada.");}catch(error){notify(error.code==="23505"?"El jugador o el lugar ya fueron registrados.":error.message,"error");await reload({quiet:true});}finally{setBusy(dom.save,false);renderSelection();}});
dom.reserve.addEventListener("click",async()=>{try{await reserveSlot(state.activeSlot.id,{isAdmin,memberPlayerId:state.member?.id});await closePlayerDrawer();await reload({quiet:true});notify("Lugar reservado.");}catch(error){notify(error.message,"error");}});
$("#blockEmptyButton").addEventListener("click",async()=>{try{await blockSlot(state.activeSlot.id,true);await closePlayerDrawer();await reload({quiet:true});notify("Casillero bloqueado.");}catch(error){notify(error.message,"error");}});
$("#moveButton").addEventListener("click",()=>{state.moveSource=state.activeSlot;closeSlot();notify("Ahora seleccioná el casillero libre de destino.");});
$("#releaseButton").addEventListener("click",async()=>{const slot=state.activeSlot;if(!slot)return;const ok=await confirmAction({title:"Liberar lugar",message:`¿Querés liberar el lugar de ${slot.display_name||"esta reserva"}?`,confirmText:"Liberar",danger:true});if(!ok)return;try{await releaseSlot(slot.id,{isAdmin,memberPlayerId:state.member?.id,tournamentDate:state.tournament.tournament_date,requiresPartner:requiresPartner()});closeSlot();await reload({quiet:true});notify("Lugar liberado.");}catch(error){notify(error.message,"error");if(!isAdmin&&whatsappWindowOpen()&&/WhatsApp/.test(error.message))if($("#whatsappButton"))$("#whatsappButton").hidden=false;}});
$("#blockButton").addEventListener("click",async()=>{try{await blockSlot(state.activeSlot.id,false);closeSlot();await reload({quiet:true});notify("Lugar desbloqueado.");}catch(error){notify(error.message,"error");}});
$("#closeDrawer").addEventListener("click",closePlayerDrawer);$("#closeSlotDrawer").addEventListener("click",closeSlot);dom.tabs.addEventListener("click",event=>{const button=event.target.closest("[data-grid-filter]");if(!button)return;state.viewFilter=button.dataset.gridFilter;renderFilter();renderGrid();});dom.gridSearch.addEventListener("input",renderGrid);$("#addPlayerButton").addEventListener("click",()=>{const instruction=$("#gridInstruction");instruction.hidden=false;dom.grid.classList.add("slot-pick-mode");instruction.scrollIntoView({behavior:"smooth",block:"center"});});$("#refreshButton").addEventListener("click",()=>reload());$("#exportGridButton")?.addEventListener("click",async()=>{const{exportRegistrationGrid}=await import("./registration_grid_export.js");return exportRegistrationGrid({data:{tournament:state.tournament,blocks:state.blocks,lines:state.lines,slots:state.slots},button:$("#exportGridButton"),wrap:$("#shareExportWrap")})});window.addEventListener("beforeunload",()=>state.unsubscribe?.());

try{state.member=isAdmin?null:await getMemberPlayer(context.user.id);if(!isAdmin&&!state.member)throw new Error("Tu usuario no está vinculado con un jugador.");state.tournaments=await listAvailableTournaments(isAdmin);const requested=new URLSearchParams(location.search).get("torneo_id")||getActiveTournament().id;const initial=state.tournaments.find(t=>t.id===requested);if(initial)await chooseTournament(initial.id);else{dom.grid.innerHTML='<div class="empty-state">Elegí el torneo desde Inicio para administrar sus inscripciones.<br><br><a class="btn primary" href="panel.html">Ir a Inicio</a></div>';dom.strip.hidden=true;}}
catch(error){showState(dom.page,error.message,"error");dom.grid.innerHTML='<div class="empty-state">No se pudo iniciar la grilla.</div>';}
