import { escapeHtml, formatDate } from "./ui.js";
import { normalizeText, normalizeGender, isGross, isAmerican, validCard, statusText, primaryScore, compareCards, compareSeriesItems, categoryForCard, scratchEligible, aggregateSeries } from "./results_service.js";

const prizeFields=[["Approach Hoyo 3","approach","3"],["Approach Hoyo 5","approach","5"],["Approach Hoyo 11","approach","11"],["Approach Hoyo 13","approach","13"],["Long Drive","long_drive"],["Precisión Drive","precision_drive"]];
export function buildWinnersReport(bundle,config){
 const allowsScratch=!isGross(bundle)&&!isAmerican(bundle),keyOf=item=>String(item.series?item.key:item.linked_player_id||item.aag_member_number||item.id||normalizeText(item.display_name));
 const special=raw=>{raw=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:{};return prizeFields.map(([label,type,hole])=>({label,winner:type==="approach"?raw.approach?.[hole]||"":raw[type]||""})).filter(x=>x.winner)};
 const seriesItems=mode=>aggregateSeries(bundle).map(original=>{let item={...original,series:true};if(mode==="series")return item;const count=mode==="best36"?2:1,chosen=[...item.cards].filter(validCard).sort((a,b)=>compareCards(bundle,a,b,false)).slice(0,count);return{...item,cards:chosen,tieCards:mode==="best36"?item.cards:chosen,roundValues:chosen.map(card=>primaryScore(bundle,card,false)),roundGross:chosen.map(card=>primaryScore(bundle,card,true)),total:chosen.length===count?chosen.reduce((sum,card)=>sum+primaryScore(bundle,card,false),0):Infinity,grossTotal:chosen.length===count?chosen.reduce((sum,card)=>sum+primaryScore(bundle,card,true),0):Infinity,validRounds:chosen.length}});
 const status=(item,mode)=>item.series?(item.validRounds>=(["series","best36"].includes(mode)?2:1)?"":"NPT"):statusText(item),score=(item,scratch)=>item.series?(scratch?item.grossTotal:item.total):primaryScore(bundle,item,scratch),sort=(items,scratch,mode)=>[...items].sort((a,b)=>mode!=="day"?compareSeriesItems(bundle,{...a,cards:a.tieCards||a.cards},{...b,cards:b.tieCards||b.cards},scratch,mode==="series"):compareCards(bundle,a,b,scratch));
 const scratchItems=(gender,mode)=>mode!=="day"?seriesItems(mode).filter(item=>normalizeGender(item.player_gender)===gender&&Number(item.official_index)>=-10&&Number(item.official_index)<=9&&!status(item,mode)):bundle.cards.filter(card=>scratchEligible(card,gender));
 const excluded=mode=>{const ids=new Set;if(!allowsScratch)return ids;[["male",config.scratchMen],["female",config.scratchWomen]].forEach(([gender,count])=>sort(scratchItems(gender,mode),true,mode).slice(0,count).forEach(item=>ids.add(keyOf(item))));return ids};
 const categoryItems=(category,mode)=>{const raw=mode!=="day"?seriesItems(mode).filter(item=>normalizeText(item.category_name)===normalizeText(category.name)):bundle.cards.filter(card=>categoryForCard(bundle,card)?.id===category.id),skip=excluded(mode);return raw.filter(item=>!skip.has(keyOf(item)))};
 const evidence=category=>{const cards=(bundle.series?bundle.seriesCards:bundle.cards).filter(card=>String(card.category_id||"")===String(category.id)||normalizeText(card.category_name)===normalizeText(category.name)),genders=cards.map(card=>normalizeGender(card.player_gender)).filter(Boolean),indexes=cards.map(card=>Number(card.official_index)).filter(Number.isFinite);return{gender:genders.filter(x=>x==="female").length>genders.filter(x=>x==="male").length?"female":"male",min:indexes.length?Math.min(...indexes):-Infinity,max:indexes.length?Math.max(...indexes):-Infinity}};
 const gender=category=>normalizeGender(category.gender)||evidence(category).gender||(/dama|mujer|femen|roja/i.test(normalizeText(category.name))?"female":"male"),limit=(category,key)=>{const value=Number(category[key]);return category[key]!==null&&category[key]!==""&&Number.isFinite(value)?value:(key==="index_min"?evidence(category).min:evidence(category).max)},categories=[...bundle.categories].sort((a,b)=>(gender(a)==="female"?0:1)-(gender(b)==="female"?0:1)||limit(b,"index_max")-limit(a,"index_max")||limit(b,"index_min")-limit(a,"index_min")||Number(b.display_order||0)-Number(a.display_order||0));
 const title=mode=>mode==="series"?"Acumulado de todas las fechas":mode==="best18"?"Mejores 18 hoyos jugados":mode==="best36"?"Mejores 36 hoyos jugados":`Ganadores de la fecha · ${bundle.tournament.name}`,header=text=>`<header><img src="escudo.png"><div><small>Villa María Golf Club</small><h1>${escapeHtml(bundle.series?.name||bundle.tournament.name)}</h1><p>${escapeHtml(text)}</p></div></header>`;
 const block=(name,items,mode,scratch=false,count=config.categoryWinners)=>{const winners=sort(items,scratch,mode).filter(item=>!status(item,mode)).slice(0,count);return winners.length?`<section class="presenter-category"><h2>${escapeHtml(name)}</h2><div>${[...winners].reverse().map((item,index)=>`<p><span class="presenter-position">${winners.length-index}º)</span><strong>${escapeHtml(item.display_name)}</strong><b>${score(item,scratch)}</b></p>`).join("")}</div></section>`:""};
 const page=mode=>{let winners="";categories.filter(c=>gender(c)==="female").forEach(c=>winners+=block(c.name,categoryItems(c,mode),mode));categories.filter(c=>gender(c)!=="female").forEach(c=>winners+=block(c.name,categoryItems(c,mode),mode));if(allowsScratch&&config.scratchWomen)winners+=block("Scratch Damas",scratchItems("female",mode),mode,true,config.scratchWomen);if(allowsScratch&&config.scratchMen)winners+=block("Scratch Caballeros",scratchItems("male",mode),mode,true,config.scratchMen);const text=title(mode);return`<section class="presenter-page">${header(text)}<div class="presenter-section-title">${escapeHtml(text)}</div><div class="presenter-winners">${winners||'<p class="presenter-empty">No hay premiados suficientes para esta clasificación.</p>'}</div><footer>Villa María Golf Club · Comisión de Torneos</footer></section>`};
 const groups=(bundle.series?bundle.rounds:[bundle.tournament]).map(round=>({round,entries:special(round.special_prizes)})).filter(x=>x.entries.length),prizes=groups.length?`<section class="presenter-page presenter-prize-page">${header("Premios especiales")}<section class="presenter-prizes"><h2>Premios especiales</h2>${groups.map(({round,entries})=>`<div class="presenter-prize-round"><h3>${escapeHtml(bundle.series?`${round.name} · ${formatDate(round.tournament_date)}`:formatDate(round.tournament_date))}</h3>${entries.map(item=>`<div class="presenter-prize"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(item.winner)}</strong></div>`).join("")}</div>`).join("")}</section><footer>Villa María Golf Club · Comisión de Torneos</footer></section>`:"";
 const modes=bundle.series?["series","best36","best18","day"]:["day"];
 return`<main class="presenter-print">${prizes}${modes.map(page).join("")}</main>`;
}
